name: dependabot

#Trigger
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          toolchain: 1.85.0

      # Installer cargo-edit avant, et mettre une layer de cache entre les deux
      # pour éviter de gaspiller des resources (même si c'est à minuit)
      - name: Update dependencies
        run: |
          cargo install cargo-edit
          cargo update
          cargo upgrade

      # La création de la PR ne se fera que si une dépendance a vu sa version
      # mise à jour, sinon c'est une PR vide, il faut faire un check de plus
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
            base: main
            commit-message: Update dependencies
            title: bot/update
            body: |
              - Dependency updates
  
              Auto-generated by [create-pull-request][1]
  
              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-dependencies
