name: CI quality check

# Trigger
on:
    pull_request:
        branches: ["*"]
        types: [opened, synchronize]

# JOBS
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                toolchain: 1.85.0
            - uses: actions/cache@v4
              id: cache
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}-cargo-
            - name: Install Dependecies
              if: steps.cache.outputs.cache-hit != 'true'
              run: make setup-install
            - run: make release

    quality-check:        
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with: 
                toolchain: 1.85.0
                components: rustfmt, clippy
            - uses: actions/cache@v4
              id: cache
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.target
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}--cargo-
            - name: Install Dependecies
              if: steps.cache.outputs.cache-hit != 'true'
              run: make setup-install
            - run: make quality-check
    