name: CI todos

# Trigger
on:
    pull_request:
        branches: ['*']
        types: [opened, synchronize]

# jobs
jobs:
    check-todos:
        name: check todos
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: check if todos exist and are linked to an issue
              run: |
                  # Search all todos
                  TODOS=$(grep -r "TODO" --exclude-dir=.git --exclude-dir=target --exclude-dir=.github --exclude="*.yml" --exclude="*.yaml" --exclude="*.md" . || true)
                  if [ -z "$TODOS" ]; then
                    echo "No TODO found"
                    exit 0
                  fi
                  echo "TODOs found:"
                  echo "$TODOS"
                  echo ""
                  #value of the list of issues nb found
                  ISSUE_NUMBERS=$(echo "$TODOS" | grep -oE 'TODO[[:space:]]*\(#[0-9]+\)' | grep -oE '[0-9]+' | sort -u || true)
                  echo "Number of the issues extracted: '$ISSUE_NUMBERS'"

                  # Check for TODOs without issue reference
                  TODOS_WITHOUT_ISSUE=$(echo "$TODOS" | grep -vE 'TODO[[:space:]]*\(#[0-9]+\)' || true)
                  if [ -n "$TODOS_WITHOUT_ISSUE" ]; then
                    echo "Error: TODOs found without issue reference (format TODO (#X)):"
                    echo "$TODOS_WITHOUT_ISSUE"
                    echo "Please fix them now or else we will find you"
                    exit 1
                  fi

                  if [ -z "$ISSUE_NUMBERS" ]; then
                    echo "Error: TODOs has been found but none are linked to issue format TODO (#X)"
                    exit 1
                  fi
                  # Ensure each issue are on Github issues
                  REPO_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f1)
                  REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
                  MISSING_ISSUES=""
                  for issue_num in $ISSUE_NUMBERS; do
                    
                    #Ensure issue exist by looking the ID from GitHub API
                    ISSUE_ID=$(curl -s \
                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$issue_num" \
                      | grep '"number"' | cut -d':' -f2 | tr -d ' ,' || true)
                    
                    # Ensure issue exist
                    if [ -z "$ISSUE_ID" ] || [ "$ISSUE_ID" != "$issue_num" ]; then
                      MISSING_ISSUES="$MISSING_ISSUES $issue_num"
                      echo "Issue #$issue_num doesn't exist"
                    else
                      echo "Issue #$issue_num exists (ID: $ISSUE_ID)"
                    fi
                  done
                  if [ -n "$MISSING_ISSUES" ]; then
                    echo "Error: Following issues are referenced in TODOs but not on github:$MISSING_ISSUES"
                    exit 1
                  fi
